"""
gen_fc_rom.py

Reads quantized_weights.json and generates fc_rom.sv containing
the fully connected layer weights and biases.

FC layer:
  Input:  200 values (8x5x5 pool2 output, flattened)
  Output: 10 class scores (one per digit 0-9)
  Weights: [10, 200] = 2000 int8 values
  Biases:  [10]      = 10   int8 values

Address scheme:
  weight: class*200 + input_idx  (0..1999)
  bias:   class                  (0..9)
"""

import json


def sv_literal(val):
    if val < 0:
        return f"-8'sd{abs(val)}"
    return f"8'sd{val}"


def load_weights(path="quantized_weights.json"):
    with open(path) as f:
        data = json.load(f)
    w = data["fc.weight"]["values"]   # [10, 200] flat = 2000 values
    b = data["fc.bias"]["values"]     # [10]
    return w, b


def generate(weights, biases):
    lines = [
        "// fc_rom.sv",
        "// Auto-generated by gen_fc_rom.py -- do not edit by hand.",
        "//",
        "// FC weights: [10, 200] = 2000 int8 values",
        "//   address = class_idx * 200 + input_idx",
        "// FC biases: [10] int8 values",
        "",
        "module fc_rom (",
        "    input  logic [10:0]       weight_addr,  // 0..1999",
        "    output logic signed [7:0] weight_out,",
        "    input  logic [3:0]        bias_addr,    // 0..9",
        "    output logic signed [7:0] bias_out",
        ");",
        "",
        "    always_comb begin",
        "        case (weight_addr)",
    ]

    for cls in range(10):
        for inp in range(200):
            addr = cls * 200 + inp
            val  = weights[addr]
            lines.append(
                f"            11'd{addr:4d}: weight_out = {sv_literal(val)};  "
                f"// class={cls} inp={inp}"
            )
    lines += [
        "            default:  weight_out = 8'sd0;",
        "        endcase",
        "    end",
        "",
        "    always_comb begin",
        "        case (bias_addr)",
    ]
    for cls in range(10):
        lines.append(
            f"            4'd{cls}: bias_out = {sv_literal(biases[cls])};  // class={cls}"
        )
    lines += [
        "            default: bias_out = 8'sd0;",
        "        endcase",
        "    end",
        "",
        "endmodule",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    weights, biases = load_weights()
    print(f"FC weights: {len(weights)} values  FC biases: {len(biases)} values")

    sv = generate(weights, biases)
    with open("fc_rom.sv", "w") as f:
        f.write(sv)
    print("Written: fc_rom.sv")
    print(f"weight_addr width: 11 bits (0..1999)")
    print(f"bias_addr width:    4 bits (0..9)")
