"""
gen_weight_rom.py

Reads quantized_weights.json and generates two files:
  - weight_rom.sv   : a SystemVerilog ROM module containing all conv1
                      weights, addressed by (out_channel, ky, kx)
  - weight_rom_check.txt : human-readable listing so you can spot-check
                           the generated values against your JSON

Usage:
    python gen_weight_rom.py
    (run from the same folder as quantized_weights.json)

Why auto-generate instead of writing the ROM by hand?
  - 36 numbers typed by hand means 36 chances for a typo
  - If you retrain the model, just re-run this script -- the ROM
    updates automatically
  - The generated file is self-documenting: each line shows the
    (oc, ky, kx) address alongside the value
"""

import json


def flat_index(oc, ky, kx, in_ch=1, kh=3, kw=3):
    """Match the row-major layout used in quantized_weights.json:
       index = ((oc * in_ch + ic) * kh + ky) * kw + kx
       For conv1, in_ch=1 and ic=0 always."""
    return ((oc * in_ch + 0) * kh + ky) * kw + kx


def load_weights(path="quantized_weights.json"):
    with open(path) as f:
        data = json.load(f)
    w = data["conv1.weight"]["values"]   # flat list of 36 int8 values
    b = data["conv1.bias"]["values"]     # flat list of 4 int8 values
    return w, b


def sv_literal(val):
    """Return a valid Verilog signed 8-bit literal for val.
    Positive/zero: 8'sd54
    Negative:     -8'sd16  (unary minus before the literal)
    """
    if val < 0:
        return f"-8'sd{abs(val)}"
    else:
        return f"8'sd{val}"


def generate_rom(weights, biases):
    """
    Address scheme:
      Weight ROM: addr = oc*9 + ky*3 + kx  (0..35)
      Bias  ROM:  addr = oc               (0..3)

    Both ROMs are combinational (no clock needed) -- just a case
    statement that maps address to value. This is the simplest
    possible ROM for an FPGA: Vivado will infer it as block RAM or
    distributed RAM automatically.
    """
    lines = []
    lines.append("// weight_rom.sv")
    lines.append("//")
    lines.append("// Auto-generated by gen_weight_rom.py -- do not edit by hand.")
    lines.append("// Re-run gen_weight_rom.py after retraining to update.")
    lines.append("//")
    lines.append("// Weight ROM: 36 entries, addressed by (oc*9 + ky*3 + kx)")
    lines.append("// Bias ROM:    4 entries, addressed by oc")
    lines.append("// All values are signed int8, matching quantize.py output.")
    lines.append("")
    lines.append("module weight_rom (")
    lines.append("    input  logic [5:0]       weight_addr,  // 0..35 (oc*9 + ky*3 + kx)")
    lines.append("    output logic signed [7:0] weight_out,")
    lines.append("    input  logic [1:0]       bias_addr,    // 0..3  (oc)")
    lines.append("    output logic signed [7:0] bias_out")
    lines.append(");")
    lines.append("")

    # Weight ROM
    lines.append("    // --- weight ROM ---")
    lines.append("    always_comb begin")
    lines.append("        case (weight_addr)")
    for oc in range(4):
        for ky in range(3):
            for kx in range(3):
                addr = oc * 9 + ky * 3 + kx
                val  = weights[flat_index(oc, ky, kx)]
                lines.append(f"            6'd{addr:2d}: weight_out = {sv_literal(val)};  // oc={oc} ky={ky} kx={kx}")
    lines.append("            default:  weight_out = 8'sd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")

    # Bias ROM
    lines.append("    // --- bias ROM ---")
    lines.append("    always_comb begin")
    lines.append("        case (bias_addr)")
    for oc in range(4):
        val = biases[oc]
        lines.append(f"            2'd{oc}: bias_out = {sv_literal(val)};  // oc={oc}")
    lines.append("            default: bias_out = 8'sd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)


def generate_check(weights, biases):
    """Human-readable listing for spot-checking against quantized_weights.json"""
    lines = ["conv1 weights (oc, ky, kx) -> int8 value", "-" * 45]
    for oc in range(4):
        for ky in range(3):
            row = []
            for kx in range(3):
                val = weights[flat_index(oc, ky, kx)]
                row.append(f"{val:4d}")
            lines.append(f"  oc={oc} ky={ky}:  {' '.join(row)}")
        lines.append("")
    lines.append("conv1 biases (oc) -> int8 value")
    lines.append("-" * 45)
    for oc in range(4):
        lines.append(f"  oc={oc}:  {biases[oc]}")
    return "\n".join(lines)


if __name__ == "__main__":
    weights, biases = load_weights()

    rom_sv = generate_rom(weights, biases)
    with open("weight_rom.sv", "w") as f:
        f.write(rom_sv)
    print("Written: weight_rom.sv")

    check_txt = generate_check(weights, biases)
    with open("weight_rom_check.txt", "w") as f:
        f.write(check_txt)
    print("Written: weight_rom_check.txt")

    # Quick sanity check: verify channel 0 kernel matches verify_mac.py output
    # Expected from your run: [-16, 54, 101, 59, 85, 126, 11, 39, 5]
    ch0 = [weights[flat_index(0, ky, kx)] for ky in range(3) for kx in range(3)]
    print(f"\nChannel 0 kernel (should be [-16, 54, 101, 59, 85, 126, 11, 39, 5]):")
    print(f"  {ch0}")
    expected = [-16, 54, 101, 59, 85, 126, 11, 39, 5]
    if ch0 == expected:
        print("  PASS: matches verify_mac.py golden values exactly")
    else:
        print("  FAIL: mismatch -- check quantized_weights.json")
