"""
gen_conv2_rom.py

Reads quantized_weights.json and generates weight_rom2.sv containing
the conv2 weights and biases.

conv2 architecture:
  8 output channels, 4 input channels, 3x3 kernel
  weight shape: [8, 4, 3, 3] = 288 values
  bias shape:   [8]

Address scheme:
  weight: oc*36 + ic*9 + ky*3 + kx  (0..287)
  bias:   oc                          (0..7)
"""

import json


def sv_literal(val):
    if val < 0:
        return f"-8'sd{abs(val)}"
    return f"8'sd{val}"


def flat_index(oc, ic, ky, kx, in_ch=4, kh=3, kw=3):
    return ((oc * in_ch + ic) * kh + ky) * kw + kx


def load_weights(path="quantized_weights.json"):
    with open(path) as f:
        data = json.load(f)
    w = data["conv2.weight"]["values"]
    b = data["conv2.bias"]["values"]
    return w, b


def generate(weights, biases):
    lines = [
        "// weight_rom2.sv",
        "// Auto-generated by gen_conv2_rom.py -- do not edit by hand.",
        "//",
        "// conv2 weights: [8, 4, 3, 3] = 288 int8 values",
        "//   address = oc*36 + ic*9 + ky*3 + kx",
        "// conv2 biases: [8] int8 values",
        "",
        "module weight_rom2 (",
        "    input  logic [8:0]        weight_addr,  // 0..287",
        "    output logic signed [7:0] weight_out,",
        "    input  logic [2:0]        bias_addr,    // 0..7",
        "    output logic signed [7:0] bias_out",
        ");",
        "",
        "    always_comb begin",
        "        case (weight_addr)",
    ]
    for oc in range(8):
        for ic in range(4):
            for ky in range(3):
                for kx in range(3):
                    addr = oc*36 + ic*9 + ky*3 + kx
                    val  = weights[flat_index(oc, ic, ky, kx)]
                    lines.append(
                        f"            9'd{addr:3d}: weight_out = {sv_literal(val)};  "
                        f"// oc={oc} ic={ic} ky={ky} kx={kx}"
                    )
    lines += [
        "            default:  weight_out = 8'sd0;",
        "        endcase",
        "    end",
        "",
        "    always_comb begin",
        "        case (bias_addr)",
    ]
    for oc in range(8):
        lines.append(
            f"            3'd{oc}: bias_out = {sv_literal(biases[oc])};  // oc={oc}"
        )
    lines += [
        "            default: bias_out = 8'sd0;",
        "        endcase",
        "    end",
        "",
        "endmodule",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    weights, biases = load_weights()
    sv = generate(weights, biases)
    with open("weight_rom2.sv", "w") as f:
        f.write(sv)
    print(f"Written: weight_rom2.sv  ({len(weights)} weights, {len(biases)} biases)")
    print(f"weight_addr width: 9 bits (0..287)")
    print(f"bias_addr width:   3 bits (0..7)")
