// input_buf.sv
//
// Holds one 28x28 quantized input image (784 signed int8 pixels) and
// returns a pixel value given a (row, col) address.
//
// The image is stored in a flat array, row-major:
//   pixel[row][col] = mem[row * 28 + col]
//
// At the start of simulation, $readmemh loads the array from
// input_image.hex (generated by gen_input_image.py). On real hardware
// this would be replaced by a UART loader that writes pixels into the
// array one by one before inference starts -- but the memory interface
// is identical either way.
//
// This is a synchronous read: the output pixel_out is registered,
// so it appears one clock cycle after the address is presented.
// That one-cycle latency is accounted for in the conv1 controller.
//
// Port summary:
//   clk        : system clock
//   row, col   : 5-bit address (0..27 each)
//   pixel_out  : registered signed int8 output

module input_buf (
    input  logic            clk,
    input  logic [4:0]      row,      // 0..27
    input  logic [4:0]      col,      // 0..27
    output logic signed [7:0] pixel_out
);

    // 784-entry array of signed bytes
    logic signed [7:0] mem [0:783];

    // Load image from hex file at simulation start.
    // gen_input_image.py writes this file; it has 784 lines,
    // one two's-complement hex byte per line, row-major order.
    initial begin
        $readmemh("input_image.hex", mem);
    end

    // Synchronous read: output registered on rising clock edge.
    // One cycle latency -- the conv1 controller must present the
    // address one cycle before it needs the pixel.
    always_ff @(posedge clk) begin
        pixel_out <= mem[row * 28 + col];
    end

endmodule
