// requant.sv
//
// Fixed-point requantization unit.
//
// Converts a raw integer accumulator (output of a MAC array) back into
// the [0, 127] int8 range by applying a calibrated scale factor, then
// ReLU-clipping. This is the key operation that makes inter-layer
// integer arithmetic work correctly.
//
// Operation:
//   scaled = (acc * MULT) >> SHIFT   (fixed-point multiply)
//   output = clip(scaled, 0, 127)    (ReLU + saturation)
//
// Parameters MULT and SHIFT come from requant_params.json (generated by
// compute_scales.py from calibration over 100 real MNIST images).
//
// Bit widths:
//   acc:    signed 20-bit (from mac_unit)
//   MULT:   16-bit unsigned constant (fits in 16 bits for all layers)
//   product: 36-bit signed (20 + 16 bits)
//   scaled: product >> SHIFT, then take low 8 bits for clip
//   output: signed 8-bit, [0, 127]
//
// This is purely combinational -- no clock needed. The output is
// registered by the layer FSM that reads it, so no extra latency
// is added to the pipeline.
//
// Per-layer parameters (from calibrated requant_params.json):
//   conv1: MULT=33691  SHIFT=24
//   conv2: MULT=38683  SHIFT=25
//   fc:    MULT=30751  SHIFT=25

module requant #(
    parameter int MULT  = 33691,  // 16-bit multiplier
    parameter int SHIFT = 24      // right-shift amount
) (
    input  logic signed [19:0] acc,     // raw MAC accumulator
    output logic signed [7:0]  out_q   // requantized int8 output
);

    // Full-width product: 20-bit signed * 16-bit unsigned = 36-bit signed
    logic signed [35:0] product;
    assign product = acc * $signed({1'b0, MULT[15:0]});

    // Arithmetic right shift and take the relevant bits
    // We need to handle the shift carefully: product >> SHIFT gives
    // the scaled value. We take bits [SHIFT+7:SHIFT] for the 8-bit result,
    // but use a wider intermediate to check for saturation.
    logic signed [19:0] scaled;
    assign scaled = product >>> SHIFT;  // arithmetic right shift

    // Clip to [0, 127]: ReLU (clip negative to 0) + saturation (clip > 127)
    always_comb begin
        if (scaled <= 0)
            out_q = 8'sd0;
        else if (scaled > 127)
            out_q = 8'sd127;
        else
            out_q = scaled[7:0];
    end

endmodule
