// weight_rom2.sv
// Auto-generated by gen_conv2_rom.py -- do not edit by hand.
//
// conv2 weights: [8, 4, 3, 3] = 288 int8 values
//   address = oc*36 + ic*9 + ky*3 + kx
// conv2 biases: [8] int8 values

module weight_rom2 (
    input  logic [8:0]        weight_addr,  // 0..287
    output logic signed [7:0] weight_out,
    input  logic [2:0]        bias_addr,    // 0..7
    output logic signed [7:0] bias_out
);

    always_comb begin
        case (weight_addr)
            9'd  0: weight_out = 8'sd4;  // oc=0 ic=0 ky=0 kx=0
            9'd  1: weight_out = -8'sd10;  // oc=0 ic=0 ky=0 kx=1
            9'd  2: weight_out = -8'sd4;  // oc=0 ic=0 ky=0 kx=2
            9'd  3: weight_out = -8'sd49;  // oc=0 ic=0 ky=1 kx=0
            9'd  4: weight_out = 8'sd8;  // oc=0 ic=0 ky=1 kx=1
            9'd  5: weight_out = 8'sd48;  // oc=0 ic=0 ky=1 kx=2
            9'd  6: weight_out = 8'sd37;  // oc=0 ic=0 ky=2 kx=0
            9'd  7: weight_out = 8'sd41;  // oc=0 ic=0 ky=2 kx=1
            9'd  8: weight_out = 8'sd20;  // oc=0 ic=0 ky=2 kx=2
            9'd  9: weight_out = -8'sd33;  // oc=0 ic=1 ky=0 kx=0
            9'd 10: weight_out = -8'sd46;  // oc=0 ic=1 ky=0 kx=1
            9'd 11: weight_out = 8'sd5;  // oc=0 ic=1 ky=0 kx=2
            9'd 12: weight_out = -8'sd45;  // oc=0 ic=1 ky=1 kx=0
            9'd 13: weight_out = 8'sd0;  // oc=0 ic=1 ky=1 kx=1
            9'd 14: weight_out = 8'sd44;  // oc=0 ic=1 ky=1 kx=2
            9'd 15: weight_out = 8'sd40;  // oc=0 ic=1 ky=2 kx=0
            9'd 16: weight_out = 8'sd39;  // oc=0 ic=1 ky=2 kx=1
            9'd 17: weight_out = 8'sd0;  // oc=0 ic=1 ky=2 kx=2
            9'd 18: weight_out = -8'sd9;  // oc=0 ic=2 ky=0 kx=0
            9'd 19: weight_out = -8'sd14;  // oc=0 ic=2 ky=0 kx=1
            9'd 20: weight_out = 8'sd14;  // oc=0 ic=2 ky=0 kx=2
            9'd 21: weight_out = -8'sd36;  // oc=0 ic=2 ky=1 kx=0
            9'd 22: weight_out = 8'sd16;  // oc=0 ic=2 ky=1 kx=1
            9'd 23: weight_out = 8'sd39;  // oc=0 ic=2 ky=1 kx=2
            9'd 24: weight_out = 8'sd67;  // oc=0 ic=2 ky=2 kx=0
            9'd 25: weight_out = 8'sd24;  // oc=0 ic=2 ky=2 kx=1
            9'd 26: weight_out = -8'sd47;  // oc=0 ic=2 ky=2 kx=2
            9'd 27: weight_out = 8'sd37;  // oc=0 ic=3 ky=0 kx=0
            9'd 28: weight_out = -8'sd15;  // oc=0 ic=3 ky=0 kx=1
            9'd 29: weight_out = -8'sd53;  // oc=0 ic=3 ky=0 kx=2
            9'd 30: weight_out = 8'sd28;  // oc=0 ic=3 ky=1 kx=0
            9'd 31: weight_out = -8'sd15;  // oc=0 ic=3 ky=1 kx=1
            9'd 32: weight_out = 8'sd8;  // oc=0 ic=3 ky=1 kx=2
            9'd 33: weight_out = -8'sd23;  // oc=0 ic=3 ky=2 kx=0
            9'd 34: weight_out = 8'sd64;  // oc=0 ic=3 ky=2 kx=1
            9'd 35: weight_out = 8'sd26;  // oc=0 ic=3 ky=2 kx=2
            9'd 36: weight_out = 8'sd13;  // oc=1 ic=0 ky=0 kx=0
            9'd 37: weight_out = -8'sd7;  // oc=1 ic=0 ky=0 kx=1
            9'd 38: weight_out = -8'sd14;  // oc=1 ic=0 ky=0 kx=2
            9'd 39: weight_out = -8'sd1;  // oc=1 ic=0 ky=1 kx=0
            9'd 40: weight_out = -8'sd4;  // oc=1 ic=0 ky=1 kx=1
            9'd 41: weight_out = -8'sd50;  // oc=1 ic=0 ky=1 kx=2
            9'd 42: weight_out = 8'sd13;  // oc=1 ic=0 ky=2 kx=0
            9'd 43: weight_out = 8'sd41;  // oc=1 ic=0 ky=2 kx=1
            9'd 44: weight_out = 8'sd9;  // oc=1 ic=0 ky=2 kx=2
            9'd 45: weight_out = -8'sd5;  // oc=1 ic=1 ky=0 kx=0
            9'd 46: weight_out = 8'sd42;  // oc=1 ic=1 ky=0 kx=1
            9'd 47: weight_out = 8'sd11;  // oc=1 ic=1 ky=0 kx=2
            9'd 48: weight_out = -8'sd2;  // oc=1 ic=1 ky=1 kx=0
            9'd 49: weight_out = 8'sd20;  // oc=1 ic=1 ky=1 kx=1
            9'd 50: weight_out = -8'sd31;  // oc=1 ic=1 ky=1 kx=2
            9'd 51: weight_out = 8'sd11;  // oc=1 ic=1 ky=2 kx=0
            9'd 52: weight_out = -8'sd13;  // oc=1 ic=1 ky=2 kx=1
            9'd 53: weight_out = 8'sd41;  // oc=1 ic=1 ky=2 kx=2
            9'd 54: weight_out = 8'sd33;  // oc=1 ic=2 ky=0 kx=0
            9'd 55: weight_out = 8'sd10;  // oc=1 ic=2 ky=0 kx=1
            9'd 56: weight_out = -8'sd22;  // oc=1 ic=2 ky=0 kx=2
            9'd 57: weight_out = 8'sd19;  // oc=1 ic=2 ky=1 kx=0
            9'd 58: weight_out = 8'sd3;  // oc=1 ic=2 ky=1 kx=1
            9'd 59: weight_out = -8'sd12;  // oc=1 ic=2 ky=1 kx=2
            9'd 60: weight_out = 8'sd11;  // oc=1 ic=2 ky=2 kx=0
            9'd 61: weight_out = 8'sd26;  // oc=1 ic=2 ky=2 kx=1
            9'd 62: weight_out = 8'sd49;  // oc=1 ic=2 ky=2 kx=2
            9'd 63: weight_out = 8'sd13;  // oc=1 ic=3 ky=0 kx=0
            9'd 64: weight_out = 8'sd5;  // oc=1 ic=3 ky=0 kx=1
            9'd 65: weight_out = 8'sd10;  // oc=1 ic=3 ky=0 kx=2
            9'd 66: weight_out = -8'sd3;  // oc=1 ic=3 ky=1 kx=0
            9'd 67: weight_out = -8'sd39;  // oc=1 ic=3 ky=1 kx=1
            9'd 68: weight_out = -8'sd18;  // oc=1 ic=3 ky=1 kx=2
            9'd 69: weight_out = -8'sd58;  // oc=1 ic=3 ky=2 kx=0
            9'd 70: weight_out = -8'sd88;  // oc=1 ic=3 ky=2 kx=1
            9'd 71: weight_out = -8'sd56;  // oc=1 ic=3 ky=2 kx=2
            9'd 72: weight_out = 8'sd18;  // oc=2 ic=0 ky=0 kx=0
            9'd 73: weight_out = 8'sd15;  // oc=2 ic=0 ky=0 kx=1
            9'd 74: weight_out = -8'sd57;  // oc=2 ic=0 ky=0 kx=2
            9'd 75: weight_out = 8'sd17;  // oc=2 ic=0 ky=1 kx=0
            9'd 76: weight_out = 8'sd7;  // oc=2 ic=0 ky=1 kx=1
            9'd 77: weight_out = 8'sd0;  // oc=2 ic=0 ky=1 kx=2
            9'd 78: weight_out = -8'sd1;  // oc=2 ic=0 ky=2 kx=0
            9'd 79: weight_out = 8'sd26;  // oc=2 ic=0 ky=2 kx=1
            9'd 80: weight_out = 8'sd42;  // oc=2 ic=0 ky=2 kx=2
            9'd 81: weight_out = 8'sd31;  // oc=2 ic=1 ky=0 kx=0
            9'd 82: weight_out = 8'sd18;  // oc=2 ic=1 ky=0 kx=1
            9'd 83: weight_out = 8'sd17;  // oc=2 ic=1 ky=0 kx=2
            9'd 84: weight_out = 8'sd10;  // oc=2 ic=1 ky=1 kx=0
            9'd 85: weight_out = 8'sd35;  // oc=2 ic=1 ky=1 kx=1
            9'd 86: weight_out = 8'sd30;  // oc=2 ic=1 ky=1 kx=2
            9'd 87: weight_out = -8'sd16;  // oc=2 ic=1 ky=2 kx=0
            9'd 88: weight_out = 8'sd2;  // oc=2 ic=1 ky=2 kx=1
            9'd 89: weight_out = 8'sd8;  // oc=2 ic=1 ky=2 kx=2
            9'd 90: weight_out = 8'sd2;  // oc=2 ic=2 ky=0 kx=0
            9'd 91: weight_out = 8'sd17;  // oc=2 ic=2 ky=0 kx=1
            9'd 92: weight_out = 8'sd5;  // oc=2 ic=2 ky=0 kx=2
            9'd 93: weight_out = 8'sd22;  // oc=2 ic=2 ky=1 kx=0
            9'd 94: weight_out = 8'sd17;  // oc=2 ic=2 ky=1 kx=1
            9'd 95: weight_out = 8'sd15;  // oc=2 ic=2 ky=1 kx=2
            9'd 96: weight_out = -8'sd43;  // oc=2 ic=2 ky=2 kx=0
            9'd 97: weight_out = -8'sd26;  // oc=2 ic=2 ky=2 kx=1
            9'd 98: weight_out = 8'sd21;  // oc=2 ic=2 ky=2 kx=2
            9'd 99: weight_out = -8'sd5;  // oc=2 ic=3 ky=0 kx=0
            9'd100: weight_out = -8'sd82;  // oc=2 ic=3 ky=0 kx=1
            9'd101: weight_out = -8'sd36;  // oc=2 ic=3 ky=0 kx=2
            9'd102: weight_out = -8'sd66;  // oc=2 ic=3 ky=1 kx=0
            9'd103: weight_out = -8'sd115;  // oc=2 ic=3 ky=1 kx=1
            9'd104: weight_out = -8'sd107;  // oc=2 ic=3 ky=1 kx=2
            9'd105: weight_out = -8'sd6;  // oc=2 ic=3 ky=2 kx=0
            9'd106: weight_out = -8'sd59;  // oc=2 ic=3 ky=2 kx=1
            9'd107: weight_out = -8'sd64;  // oc=2 ic=3 ky=2 kx=2
            9'd108: weight_out = -8'sd17;  // oc=3 ic=0 ky=0 kx=0
            9'd109: weight_out = 8'sd30;  // oc=3 ic=0 ky=0 kx=1
            9'd110: weight_out = 8'sd32;  // oc=3 ic=0 ky=0 kx=2
            9'd111: weight_out = 8'sd14;  // oc=3 ic=0 ky=1 kx=0
            9'd112: weight_out = 8'sd62;  // oc=3 ic=0 ky=1 kx=1
            9'd113: weight_out = -8'sd56;  // oc=3 ic=0 ky=1 kx=2
            9'd114: weight_out = 8'sd60;  // oc=3 ic=0 ky=2 kx=0
            9'd115: weight_out = -8'sd33;  // oc=3 ic=0 ky=2 kx=1
            9'd116: weight_out = -8'sd18;  // oc=3 ic=0 ky=2 kx=2
            9'd117: weight_out = -8'sd61;  // oc=3 ic=1 ky=0 kx=0
            9'd118: weight_out = 8'sd21;  // oc=3 ic=1 ky=0 kx=1
            9'd119: weight_out = 8'sd37;  // oc=3 ic=1 ky=0 kx=2
            9'd120: weight_out = -8'sd9;  // oc=3 ic=1 ky=1 kx=0
            9'd121: weight_out = 8'sd45;  // oc=3 ic=1 ky=1 kx=1
            9'd122: weight_out = -8'sd47;  // oc=3 ic=1 ky=1 kx=2
            9'd123: weight_out = 8'sd53;  // oc=3 ic=1 ky=2 kx=0
            9'd124: weight_out = 8'sd5;  // oc=3 ic=1 ky=2 kx=1
            9'd125: weight_out = -8'sd67;  // oc=3 ic=1 ky=2 kx=2
            9'd126: weight_out = -8'sd5;  // oc=3 ic=2 ky=0 kx=0
            9'd127: weight_out = 8'sd27;  // oc=3 ic=2 ky=0 kx=1
            9'd128: weight_out = -8'sd9;  // oc=3 ic=2 ky=0 kx=2
            9'd129: weight_out = 8'sd6;  // oc=3 ic=2 ky=1 kx=0
            9'd130: weight_out = 8'sd22;  // oc=3 ic=2 ky=1 kx=1
            9'd131: weight_out = -8'sd44;  // oc=3 ic=2 ky=1 kx=2
            9'd132: weight_out = 8'sd11;  // oc=3 ic=2 ky=2 kx=0
            9'd133: weight_out = -8'sd26;  // oc=3 ic=2 ky=2 kx=1
            9'd134: weight_out = -8'sd14;  // oc=3 ic=2 ky=2 kx=2
            9'd135: weight_out = -8'sd45;  // oc=3 ic=3 ky=0 kx=0
            9'd136: weight_out = -8'sd51;  // oc=3 ic=3 ky=0 kx=1
            9'd137: weight_out = -8'sd21;  // oc=3 ic=3 ky=0 kx=2
            9'd138: weight_out = -8'sd42;  // oc=3 ic=3 ky=1 kx=0
            9'd139: weight_out = -8'sd6;  // oc=3 ic=3 ky=1 kx=1
            9'd140: weight_out = 8'sd16;  // oc=3 ic=3 ky=1 kx=2
            9'd141: weight_out = -8'sd7;  // oc=3 ic=3 ky=2 kx=0
            9'd142: weight_out = 8'sd5;  // oc=3 ic=3 ky=2 kx=1
            9'd143: weight_out = 8'sd29;  // oc=3 ic=3 ky=2 kx=2
            9'd144: weight_out = 8'sd35;  // oc=4 ic=0 ky=0 kx=0
            9'd145: weight_out = 8'sd62;  // oc=4 ic=0 ky=0 kx=1
            9'd146: weight_out = 8'sd65;  // oc=4 ic=0 ky=0 kx=2
            9'd147: weight_out = -8'sd59;  // oc=4 ic=0 ky=1 kx=0
            9'd148: weight_out = -8'sd86;  // oc=4 ic=0 ky=1 kx=1
            9'd149: weight_out = -8'sd75;  // oc=4 ic=0 ky=1 kx=2
            9'd150: weight_out = 8'sd13;  // oc=4 ic=0 ky=2 kx=0
            9'd151: weight_out = -8'sd15;  // oc=4 ic=0 ky=2 kx=1
            9'd152: weight_out = 8'sd10;  // oc=4 ic=0 ky=2 kx=2
            9'd153: weight_out = -8'sd5;  // oc=4 ic=1 ky=0 kx=0
            9'd154: weight_out = 8'sd22;  // oc=4 ic=1 ky=0 kx=1
            9'd155: weight_out = 8'sd65;  // oc=4 ic=1 ky=0 kx=2
            9'd156: weight_out = -8'sd35;  // oc=4 ic=1 ky=1 kx=0
            9'd157: weight_out = -8'sd64;  // oc=4 ic=1 ky=1 kx=1
            9'd158: weight_out = -8'sd61;  // oc=4 ic=1 ky=1 kx=2
            9'd159: weight_out = 8'sd24;  // oc=4 ic=1 ky=2 kx=0
            9'd160: weight_out = 8'sd38;  // oc=4 ic=1 ky=2 kx=1
            9'd161: weight_out = 8'sd5;  // oc=4 ic=1 ky=2 kx=2
            9'd162: weight_out = -8'sd2;  // oc=4 ic=2 ky=0 kx=0
            9'd163: weight_out = 8'sd39;  // oc=4 ic=2 ky=0 kx=1
            9'd164: weight_out = 8'sd38;  // oc=4 ic=2 ky=0 kx=2
            9'd165: weight_out = -8'sd56;  // oc=4 ic=2 ky=1 kx=0
            9'd166: weight_out = -8'sd109;  // oc=4 ic=2 ky=1 kx=1
            9'd167: weight_out = -8'sd77;  // oc=4 ic=2 ky=1 kx=2
            9'd168: weight_out = 8'sd71;  // oc=4 ic=2 ky=2 kx=0
            9'd169: weight_out = 8'sd52;  // oc=4 ic=2 ky=2 kx=1
            9'd170: weight_out = 8'sd37;  // oc=4 ic=2 ky=2 kx=2
            9'd171: weight_out = -8'sd19;  // oc=4 ic=3 ky=0 kx=0
            9'd172: weight_out = -8'sd18;  // oc=4 ic=3 ky=0 kx=1
            9'd173: weight_out = -8'sd9;  // oc=4 ic=3 ky=0 kx=2
            9'd174: weight_out = 8'sd15;  // oc=4 ic=3 ky=1 kx=0
            9'd175: weight_out = 8'sd47;  // oc=4 ic=3 ky=1 kx=1
            9'd176: weight_out = 8'sd59;  // oc=4 ic=3 ky=1 kx=2
            9'd177: weight_out = -8'sd10;  // oc=4 ic=3 ky=2 kx=0
            9'd178: weight_out = -8'sd26;  // oc=4 ic=3 ky=2 kx=1
            9'd179: weight_out = -8'sd23;  // oc=4 ic=3 ky=2 kx=2
            9'd180: weight_out = 8'sd43;  // oc=5 ic=0 ky=0 kx=0
            9'd181: weight_out = -8'sd4;  // oc=5 ic=0 ky=0 kx=1
            9'd182: weight_out = 8'sd34;  // oc=5 ic=0 ky=0 kx=2
            9'd183: weight_out = 8'sd26;  // oc=5 ic=0 ky=1 kx=0
            9'd184: weight_out = 8'sd34;  // oc=5 ic=0 ky=1 kx=1
            9'd185: weight_out = 8'sd47;  // oc=5 ic=0 ky=1 kx=2
            9'd186: weight_out = -8'sd26;  // oc=5 ic=0 ky=2 kx=0
            9'd187: weight_out = -8'sd30;  // oc=5 ic=0 ky=2 kx=1
            9'd188: weight_out = -8'sd95;  // oc=5 ic=0 ky=2 kx=2
            9'd189: weight_out = 8'sd27;  // oc=5 ic=1 ky=0 kx=0
            9'd190: weight_out = 8'sd37;  // oc=5 ic=1 ky=0 kx=1
            9'd191: weight_out = 8'sd22;  // oc=5 ic=1 ky=0 kx=2
            9'd192: weight_out = 8'sd0;  // oc=5 ic=1 ky=1 kx=0
            9'd193: weight_out = 8'sd13;  // oc=5 ic=1 ky=1 kx=1
            9'd194: weight_out = 8'sd21;  // oc=5 ic=1 ky=1 kx=2
            9'd195: weight_out = -8'sd41;  // oc=5 ic=1 ky=2 kx=0
            9'd196: weight_out = -8'sd26;  // oc=5 ic=1 ky=2 kx=1
            9'd197: weight_out = -8'sd64;  // oc=5 ic=1 ky=2 kx=2
            9'd198: weight_out = 8'sd45;  // oc=5 ic=2 ky=0 kx=0
            9'd199: weight_out = -8'sd6;  // oc=5 ic=2 ky=0 kx=1
            9'd200: weight_out = 8'sd61;  // oc=5 ic=2 ky=0 kx=2
            9'd201: weight_out = -8'sd8;  // oc=5 ic=2 ky=1 kx=0
            9'd202: weight_out = -8'sd5;  // oc=5 ic=2 ky=1 kx=1
            9'd203: weight_out = 8'sd2;  // oc=5 ic=2 ky=1 kx=2
            9'd204: weight_out = -8'sd68;  // oc=5 ic=2 ky=2 kx=0
            9'd205: weight_out = -8'sd76;  // oc=5 ic=2 ky=2 kx=1
            9'd206: weight_out = -8'sd72;  // oc=5 ic=2 ky=2 kx=2
            9'd207: weight_out = -8'sd24;  // oc=5 ic=3 ky=0 kx=0
            9'd208: weight_out = -8'sd42;  // oc=5 ic=3 ky=0 kx=1
            9'd209: weight_out = -8'sd10;  // oc=5 ic=3 ky=0 kx=2
            9'd210: weight_out = -8'sd17;  // oc=5 ic=3 ky=1 kx=0
            9'd211: weight_out = -8'sd29;  // oc=5 ic=3 ky=1 kx=1
            9'd212: weight_out = 8'sd8;  // oc=5 ic=3 ky=1 kx=2
            9'd213: weight_out = 8'sd6;  // oc=5 ic=3 ky=2 kx=0
            9'd214: weight_out = 8'sd22;  // oc=5 ic=3 ky=2 kx=1
            9'd215: weight_out = 8'sd62;  // oc=5 ic=3 ky=2 kx=2
            9'd216: weight_out = 8'sd30;  // oc=6 ic=0 ky=0 kx=0
            9'd217: weight_out = -8'sd38;  // oc=6 ic=0 ky=0 kx=1
            9'd218: weight_out = -8'sd110;  // oc=6 ic=0 ky=0 kx=2
            9'd219: weight_out = -8'sd34;  // oc=6 ic=0 ky=1 kx=0
            9'd220: weight_out = -8'sd77;  // oc=6 ic=0 ky=1 kx=1
            9'd221: weight_out = 8'sd55;  // oc=6 ic=0 ky=1 kx=2
            9'd222: weight_out = -8'sd53;  // oc=6 ic=0 ky=2 kx=0
            9'd223: weight_out = -8'sd21;  // oc=6 ic=0 ky=2 kx=1
            9'd224: weight_out = 8'sd42;  // oc=6 ic=0 ky=2 kx=2
            9'd225: weight_out = 8'sd54;  // oc=6 ic=1 ky=0 kx=0
            9'd226: weight_out = -8'sd9;  // oc=6 ic=1 ky=0 kx=1
            9'd227: weight_out = -8'sd66;  // oc=6 ic=1 ky=0 kx=2
            9'd228: weight_out = 8'sd4;  // oc=6 ic=1 ky=1 kx=0
            9'd229: weight_out = -8'sd76;  // oc=6 ic=1 ky=1 kx=1
            9'd230: weight_out = 8'sd43;  // oc=6 ic=1 ky=1 kx=2
            9'd231: weight_out = -8'sd41;  // oc=6 ic=1 ky=2 kx=0
            9'd232: weight_out = -8'sd20;  // oc=6 ic=1 ky=2 kx=1
            9'd233: weight_out = 8'sd17;  // oc=6 ic=1 ky=2 kx=2
            9'd234: weight_out = 8'sd34;  // oc=6 ic=2 ky=0 kx=0
            9'd235: weight_out = -8'sd61;  // oc=6 ic=2 ky=0 kx=1
            9'd236: weight_out = -8'sd88;  // oc=6 ic=2 ky=0 kx=2
            9'd237: weight_out = -8'sd85;  // oc=6 ic=2 ky=1 kx=0
            9'd238: weight_out = -8'sd54;  // oc=6 ic=2 ky=1 kx=1
            9'd239: weight_out = 8'sd79;  // oc=6 ic=2 ky=1 kx=2
            9'd240: weight_out = -8'sd64;  // oc=6 ic=2 ky=2 kx=0
            9'd241: weight_out = -8'sd24;  // oc=6 ic=2 ky=2 kx=1
            9'd242: weight_out = 8'sd33;  // oc=6 ic=2 ky=2 kx=2
            9'd243: weight_out = 8'sd57;  // oc=6 ic=3 ky=0 kx=0
            9'd244: weight_out = 8'sd61;  // oc=6 ic=3 ky=0 kx=1
            9'd245: weight_out = 8'sd120;  // oc=6 ic=3 ky=0 kx=2
            9'd246: weight_out = 8'sd127;  // oc=6 ic=3 ky=1 kx=0
            9'd247: weight_out = 8'sd109;  // oc=6 ic=3 ky=1 kx=1
            9'd248: weight_out = 8'sd37;  // oc=6 ic=3 ky=1 kx=2
            9'd249: weight_out = 8'sd75;  // oc=6 ic=3 ky=2 kx=0
            9'd250: weight_out = 8'sd54;  // oc=6 ic=3 ky=2 kx=1
            9'd251: weight_out = -8'sd50;  // oc=6 ic=3 ky=2 kx=2
            9'd252: weight_out = 8'sd49;  // oc=7 ic=0 ky=0 kx=0
            9'd253: weight_out = -8'sd3;  // oc=7 ic=0 ky=0 kx=1
            9'd254: weight_out = -8'sd32;  // oc=7 ic=0 ky=0 kx=2
            9'd255: weight_out = 8'sd36;  // oc=7 ic=0 ky=1 kx=0
            9'd256: weight_out = -8'sd32;  // oc=7 ic=0 ky=1 kx=1
            9'd257: weight_out = -8'sd43;  // oc=7 ic=0 ky=1 kx=2
            9'd258: weight_out = 8'sd41;  // oc=7 ic=0 ky=2 kx=0
            9'd259: weight_out = -8'sd32;  // oc=7 ic=0 ky=2 kx=1
            9'd260: weight_out = -8'sd27;  // oc=7 ic=0 ky=2 kx=2
            9'd261: weight_out = 8'sd27;  // oc=7 ic=1 ky=0 kx=0
            9'd262: weight_out = 8'sd36;  // oc=7 ic=1 ky=0 kx=1
            9'd263: weight_out = -8'sd49;  // oc=7 ic=1 ky=0 kx=2
            9'd264: weight_out = 8'sd50;  // oc=7 ic=1 ky=1 kx=0
            9'd265: weight_out = 8'sd22;  // oc=7 ic=1 ky=1 kx=1
            9'd266: weight_out = -8'sd52;  // oc=7 ic=1 ky=1 kx=2
            9'd267: weight_out = 8'sd64;  // oc=7 ic=1 ky=2 kx=0
            9'd268: weight_out = 8'sd14;  // oc=7 ic=1 ky=2 kx=1
            9'd269: weight_out = -8'sd42;  // oc=7 ic=1 ky=2 kx=2
            9'd270: weight_out = 8'sd34;  // oc=7 ic=2 ky=0 kx=0
            9'd271: weight_out = -8'sd33;  // oc=7 ic=2 ky=0 kx=1
            9'd272: weight_out = -8'sd52;  // oc=7 ic=2 ky=0 kx=2
            9'd273: weight_out = 8'sd9;  // oc=7 ic=2 ky=1 kx=0
            9'd274: weight_out = -8'sd41;  // oc=7 ic=2 ky=1 kx=1
            9'd275: weight_out = -8'sd30;  // oc=7 ic=2 ky=1 kx=2
            9'd276: weight_out = 8'sd30;  // oc=7 ic=2 ky=2 kx=0
            9'd277: weight_out = -8'sd51;  // oc=7 ic=2 ky=2 kx=1
            9'd278: weight_out = -8'sd27;  // oc=7 ic=2 ky=2 kx=2
            9'd279: weight_out = -8'sd48;  // oc=7 ic=3 ky=0 kx=0
            9'd280: weight_out = -8'sd17;  // oc=7 ic=3 ky=0 kx=1
            9'd281: weight_out = 8'sd21;  // oc=7 ic=3 ky=0 kx=2
            9'd282: weight_out = -8'sd27;  // oc=7 ic=3 ky=1 kx=0
            9'd283: weight_out = -8'sd4;  // oc=7 ic=3 ky=1 kx=1
            9'd284: weight_out = 8'sd17;  // oc=7 ic=3 ky=1 kx=2
            9'd285: weight_out = 8'sd1;  // oc=7 ic=3 ky=2 kx=0
            9'd286: weight_out = 8'sd67;  // oc=7 ic=3 ky=2 kx=1
            9'd287: weight_out = -8'sd4;  // oc=7 ic=3 ky=2 kx=2
            default:  weight_out = 8'sd0;
        endcase
    end

    always_comb begin
        case (bias_addr)
            3'd0: bias_out = -8'sd127;  // oc=0
            3'd1: bias_out = -8'sd33;  // oc=1
            3'd2: bias_out = 8'sd29;  // oc=2
            3'd3: bias_out = -8'sd94;  // oc=3
            3'd4: bias_out = -8'sd32;  // oc=4
            3'd5: bias_out = 8'sd70;  // oc=5
            3'd6: bias_out = -8'sd15;  // oc=6
            3'd7: bias_out = 8'sd93;  // oc=7
            default: bias_out = 8'sd0;
        endcase
    end

endmodule