// weight_rom.sv
//
// Auto-generated by gen_weight_rom.py -- do not edit by hand.
// Re-run gen_weight_rom.py after retraining to update.
//
// Weight ROM: 36 entries, addressed by (oc*9 + ky*3 + kx)
// Bias ROM:    4 entries, addressed by oc
// All values are signed int8, matching quantize.py output.

module weight_rom (
    input  logic [5:0]       weight_addr,  // 0..35 (oc*9 + ky*3 + kx)
    output logic signed [7:0] weight_out,
    input  logic [1:0]       bias_addr,    // 0..3  (oc)
    output logic signed [7:0] bias_out
);

    // --- weight ROM ---
    always_comb begin
        case (weight_addr)
            6'd 0: weight_out = -8'sd16;  // oc=0 ky=0 kx=0
            6'd 1: weight_out = 8'sd54;  // oc=0 ky=0 kx=1
            6'd 2: weight_out = 8'sd101;  // oc=0 ky=0 kx=2
            6'd 3: weight_out = 8'sd59;  // oc=0 ky=1 kx=0
            6'd 4: weight_out = 8'sd85;  // oc=0 ky=1 kx=1
            6'd 5: weight_out = 8'sd126;  // oc=0 ky=1 kx=2
            6'd 6: weight_out = 8'sd11;  // oc=0 ky=2 kx=0
            6'd 7: weight_out = 8'sd39;  // oc=0 ky=2 kx=1
            6'd 8: weight_out = 8'sd5;  // oc=0 ky=2 kx=2
            6'd 9: weight_out = 8'sd9;  // oc=1 ky=0 kx=0
            6'd10: weight_out = 8'sd39;  // oc=1 ky=0 kx=1
            6'd11: weight_out = 8'sd97;  // oc=1 ky=0 kx=2
            6'd12: weight_out = 8'sd52;  // oc=1 ky=1 kx=0
            6'd13: weight_out = 8'sd81;  // oc=1 ky=1 kx=1
            6'd14: weight_out = 8'sd21;  // oc=1 ky=1 kx=2
            6'd15: weight_out = 8'sd88;  // oc=1 ky=2 kx=0
            6'd16: weight_out = 8'sd95;  // oc=1 ky=2 kx=1
            6'd17: weight_out = -8'sd44;  // oc=1 ky=2 kx=2
            6'd18: weight_out = -8'sd70;  // oc=2 ky=0 kx=0
            6'd19: weight_out = -8'sd41;  // oc=2 ky=0 kx=1
            6'd20: weight_out = -8'sd7;  // oc=2 ky=0 kx=2
            6'd21: weight_out = 8'sd49;  // oc=2 ky=1 kx=0
            6'd22: weight_out = 8'sd47;  // oc=2 ky=1 kx=1
            6'd23: weight_out = 8'sd103;  // oc=2 ky=1 kx=2
            6'd24: weight_out = 8'sd88;  // oc=2 ky=2 kx=0
            6'd25: weight_out = 8'sd120;  // oc=2 ky=2 kx=1
            6'd26: weight_out = 8'sd91;  // oc=2 ky=2 kx=2
            6'd27: weight_out = 8'sd63;  // oc=3 ky=0 kx=0
            6'd28: weight_out = 8'sd67;  // oc=3 ky=0 kx=1
            6'd29: weight_out = -8'sd56;  // oc=3 ky=0 kx=2
            6'd30: weight_out = 8'sd66;  // oc=3 ky=1 kx=0
            6'd31: weight_out = -8'sd45;  // oc=3 ky=1 kx=1
            6'd32: weight_out = -8'sd88;  // oc=3 ky=1 kx=2
            6'd33: weight_out = -8'sd62;  // oc=3 ky=2 kx=0
            6'd34: weight_out = -8'sd127;  // oc=3 ky=2 kx=1
            6'd35: weight_out = 8'sd16;  // oc=3 ky=2 kx=2
            default:  weight_out = 8'sd0;
        endcase
    end

    // --- bias ROM ---
    always_comb begin
        case (bias_addr)
            2'd0: bias_out = -8'sd2;  // oc=0
            2'd1: bias_out = 8'sd55;  // oc=1
            2'd2: bias_out = -8'sd3;  // oc=2
            2'd3: bias_out = 8'sd127;  // oc=3
            default: bias_out = 8'sd0;
        endcase
    end

endmodule